### PR TITLE
LL-115 connect to wi-fi with device

### PR DESCRIPTION
**Pull request by aematei**
# Description

What needs to be done

interface that allows users to connect to Wi-Fi with their device
Why it needs to be done

allows the device to communicate with the app and DB
Acceptance Criteria

Given page in app which allows users to connect to Wi-Fi with their device Then device connects to Wi-Fi 
Stakeholders

Alex
Relevant Pictures (if applicable)

Subsequent #LL-115

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist (when relevant):

- [ ] My code follows the style guidelines of this project

    [TypeScript](https://google.github.io/styleguide/tsguide.html)
[Python](https://peps.python.org/pep-0008/)
[Schema](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/forefront-2010/ee652242(v=vs.100))
- [ ] I have included a reviewer on the pull request [*Replace this text with the reviewer*]
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by aematei** [comment]
Hey @pogi7, I'm not sure what happened, but I used the incorrect branch name for this branch (LL-139 instead of LL-115). Do you have any advice on how I can change it?

**Comment by pogi7** [comment]
> Hey @pogi7, I'm not sure what happened, but I used the incorrect branch name for this branch (LL-139 instead of LL-115). Do you have any advice on how I can change it?

@aematei Just make a new PR with the correct branch name and close this PR.

`git switch LL-139`
`git checkout -b LL-115`
Make a new PR with the source branch as LL-115 and the target branch as master

**Comment by aematei** [comment]
> > Hey @pogi7, I'm not sure what happened, but I used the incorrect branch name for this branch (LL-139 instead of LL-115). Do you have any advice on how I can change it?
> 
> @aematei Just make a new PR with the correct branch name and close this PR.
> 
> `git switch LL-139` `git checkout -b LL-115` Make a new PR with the source branch as LL-115 and the target branch as master

@pogi7  okay I'll try it, thanks! Should I delete the old branch/pr once I do this?

**Comment by pogi7** [comment]
@aematei Yeah delete the old branch and close this PR

**Pull request closed without merging**
