### PR TITLE
LL-169 Use MongoDB API to get and set brightness

### PR DESCRIPTION
**Pull request by aematei**
… (switch requests to urequests for embedded environment)

# Description

Please include a summary of the change and its subsequent issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Subsequent # LL-169

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
```
cd controller
source .venv/Scripts/activate
pip install -r requirements.txt
python -m pytest test/mongodb/test_brightness.py
```
# Checklist (when relevant):

- [X] My code follows the style guidelines of this project

[TypeScript](https://google.github.io/styleguide/tsguide.html)
[Python](https://peps.python.org/pep-0008/)
[Schema](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/forefront-2010/ee652242(v=vs.100))
- [x] I have included a reviewer on the pull request @pogi7 @WhenitStarted 
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by aematei** [comment]
@pogi7 It looks like my new changes to the mongodb code are clashing with the workflow tests. Do you think you can advise me on how to update them, when you have a chance? Since we don't have a mongodb driver for micropython, I'm utilizing mongodb's Data API, which has me using a different entry point from the one you used earlier.

**Comment by aematei** [comment]
Hey @pogi7, my latest commit is passing tests, we just need to add the new Data API key to our secrets context in GH. Let me know when you're available so we can add it.

**Comment by aematei** [comment]
@pogi7 Looks like I'm getting getting an error around the `MONGO_DAPI_URL` secrets env variable. I'm trying to see if there is anything on my end, can you check if the secret you added has the same name?

```
________________ ERROR collecting test/mongodb/test_lumongo.py _________________
test/mongodb/test_lumongo.py:4: in <module>
    from src.mongodb.lumongo import _findOneRequestBody,_updateOneRequestBody, findOne, updateOne
src/mongodb/lumongo.py:24: in <module>
    MONGO_DAPI_URL = f'{os.environ["MONGO_DAPI_URL"]}'
/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/os.py:680: in __getitem__
    raise KeyError(key) from None
E   KeyError: 'MONGO_DAPI_URL'
```

**Review by pogi7 — APPROVED** [review]
lgtm

**Pull request merged**
