### PR TITLE
LL-95: added microsoft sso config files

### PR DESCRIPTION
**Pull request by erikajledesma**
# Description

Please include a summary of the change and its subsequent issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

What needs to be done
When users log into luminosity-led, this story would allow users to log in with their Microsoft account.  

Why it needs to be done
This allows users to sign with their Microsoft credentials rather than their luminosity-led credentials.  It also makes it so users don’t need to input their credentials when logging in.

Run `npm install @azure/msal-node` to install Microsoft auth library.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

In `ThirdParty.tsx`, the call to the route `/auth/signin` in MicrosoftLogin leads to an empty page and does not trigger Azure AD sign in.

# Checklist (when relevant):

- [ ] My code follows the style guidelines of this project

    [TypeScript](https://google.github.io/styleguide/tsguide.html)
[Python](https://peps.python.org/pep-0008/)
[Schema](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/forefront-2010/ee652242(v=vs.100))
- [x] I have included a reviewer on the pull request [*Replace this text with the reviewer*]
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Verus20 — CHANGES_REQUESTED** [review]
Some comments on security

**Review by pogi7 — CHANGES_REQUESTED** [review]
@erikajledesma The code looks good, but unfortunately we can't use it in the `client` directory.  (This doesn't include the `src/components/ThirdParty.tsx` code.  That's fine where it's at.)

For future reference, anything that works with user authentication or secrets should be handled by the `server` directory:
https://stackoverflow.com/questions/48699820/how-do-i-hide-api-key-in-create-react-app

I don't know why you're using Javascript for the implementation when the architecture uses Typescript.  Change it when you get a chance.
TODO:
1.  Move code to `server` directory except `ThirdParty.tsx`
2.  Change to Typescript

You can look at this for inspiration:
https://github.com/Azure-Samples/ms-identity-javascript-nodejs-tutorial/blob/main/1-Authentication/1-sign-in/README.md

https://learn.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code#web-applications

**Review by Verus20 — APPROVED** [review]
Looks good, nice job on adding these changes Erika

**Review by pogi7 — APPROVED** [review]
lgtm

**Pull request merged**
